name: Auto Split Code File

on:
  push:
    paths:
      - 'main_code.py'

jobs:
  split-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Split the file
      run: |
        python3 - <<PY
        with open('main_code.py', 'r') as f:
            lines = f.readlines()

        split_line = 2400
        2part1_lines = lines[:split_line]
        2_lines = lines[split_line:]

        with open('2part1.py', 'w') as f:
            f.writelines(2_lines)

        with open('2.py', 'w') as f:
            f.write(f"# Continuation from line {split_line + 1}\n")
            f.writelines(2_lines)

        print(f"Split complete: {len(part1_lines)} + {len(_lines)} lines")
        PY

    - name: Commit split files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add 2part1.py 2.py
        git diff --staged --quiet || git commit -m "Auto-split code files"
        git push
